version: '3.8'
services:
  # Django app
  backend_analytics:
    container_name: boomslag_ms_analytics
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8016"
    volumes:
      - .:/app
    ports:
      - 8016:8016
    depends_on:
      - db_analytics
      - redis
  # Event Queue Kafka
  queue_analytics:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db_analytics
  # Database (PostgreSQL)
  db_analytics:
    image: postgres
    container_name: django_analytics_api_postgresql
    restart: always
    environment:
      POSTGRES_DB: boomslag_analytics_db
      POSTGRES_USER: boomslag
      POSTGRES_PASSWORD: postgres
    ports:
      - 5448:5432
    volumes:
      - .dbdata:/var/lib/postgresql
  # Redis Cache
  redis:
    image: redis
    container_name: django_analytics_api_redis
    ports:
      - 6345:6379