version: '3.8'
services:
  # Django app
  email_backend:
    container_name: boomslag_ms_email
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/app
    ports:
      - 8001:8001
    depends_on:
      - db_email
  # Event Queue Kafka
  email_queue:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db_email
  # Database (PostgreSQL)
  db_email:
    image: postgres
    container_name: django_email_api_postgresql
    restart: always
    environment:
      POSTGRES_DB: boomslag_email_db
      POSTGRES_USER: boomslag
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    volumes:
      - .dbdata:/var/lib/postgresql
  # Redis Cache
  redis:
    image: redis
    container_name: django_email_api_redis
    ports:
      - 6381:6379