version: '3.8'
services:
  # Django app
  backend_search:
    container_name: boomslag_ms_search
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8007"
    volumes:
      - .:/app
    ports:
      - 8007:8007
    depends_on:
      - db_search
      - redis
  # Event Queue Kafka
  queue_search:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db_search
  # Database (PostgreSQL)
  db_search:
    image: postgres
    container_name: django_search_api_postgresql
    restart: always
    environment:
      POSTGRES_DB: boomslag_search_db
      POSTGRES_USER: boomslag
      POSTGRES_PASSWORD: postgres
    ports:
      - 5439:5432
    volumes:
      - .dbdata:/var/lib/postgresql
  # Redis Cache
  redis:
    image: redis
    container_name: django_search_api_redis
    ports:
      - 6386:6379