version: '3.8'
services:
  # Django app
  backend_library:
    container_name: boomslag_ms_library
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8011"
    volumes:
      - .:/app
    ports:
      - 8011:8011
    depends_on:
      - db_library
      - redis
  # Event Queue Kafka
  library_queue:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db_library
  # Database (PostgreSQL)
  db_library:
    image: postgres
    container_name: django_library_api_postgresql
    restart: always
    environment:
      POSTGRES_DB: boomslag_library_db
      POSTGRES_USER: boomslag
      POSTGRES_PASSWORD: postgres
    ports:
      - 5443:5432
    volumes:
      - .dbdata:/var/lib/postgresql
  # Redis Cache
  redis:
    image: redis
    container_name: django_library_api_redis
    ports:
      - 6340:6379