version: '3.8'
services:
  # Django app
  backend_blog:
    container_name: boomslag_ms_blog
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8005"
    volumes:
      - .:/app
    ports:
      - 8005:8005
    depends_on:
      - db_blog
      - redis
  # Event Queue Kafka
  queue_blog:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db_blog
  # Database (PostgreSQL)
  db_blog:
    image: postgres
    container_name: django_blog_api_postgresql
    restart: always
    environment:
      POSTGRES_DB: boomslag_blog_db
      POSTGRES_USER: boomslag
      POSTGRES_PASSWORD: postgres
    ports:
      - 5437:5432
    volumes:
      - .dbdata:/var/lib/postgresql
  # Redis Cache
  redis:
    image: redis
    container_name: django_blog_api_redis
    ports:
      - 6384:6379