version: '3.8'
services:
  # Django app
  backend_wishlist:
    container_name: boomslag_ms_wishlist
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8006"
    volumes:
      - .:/app
    ports:
      - 8006:8006
    depends_on:
      - db_wishlist
      - redis
  # Event Queue Kafka
  wishlist_queue:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db_wishlist
  # Database (PostgreSQL)
  db_wishlist:
    image: postgres
    container_name: django_wishlist_api_postgresql
    restart: always
    environment:
      POSTGRES_DB: boomslag_wishlist_db
      POSTGRES_USER: boomslag
      POSTGRES_PASSWORD: postgres
    ports:
      - 5438:5432
    volumes:
      - .dbdata:/var/lib/postgresql
  # Redis Cache
  redis:
    image: redis
    container_name: django_wishlist_api_redis
    ports:
      - 6385:6379